# Generated by Django 3.1.1 on 2020-11-09 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No information', max_length=50)),
                ('content', models.TextField(default='No information')),
                ('authour', models.CharField(default='No information', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='newspaper_app.category')),
            ],
        ),
    ]
