# Generated by Django 3.1.2 on 2020-11-12 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0003_auto_20201112_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date.today, max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date.today, max_length=8),
        ),
    ]
