# Generated by Django 3.1.2 on 2020-11-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0007_auto_20201117_1519'),
        ('newspaper_app', '0007_auto_20201117_1353'),
    ]

    operations = [
    ]
