# Generated by Django 3.1.2 on 2020-11-24 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0008_merge_20201122_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.date.today, max_length=8, null=True),
        ),
    ]
